### ISSUE TITLE
Documentation project in Confluence

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#13]
High level description of the project with screenshot from Dataflow to explain the goaland what is done. The documentation should be written here
https://confluence.axa.com/confluence/display/KBData/Preparation+of+NLP+models+and+pipelines+on+Google+Cloud+Platform

a good example is this one:
https://confluence.axa.com/confluence/pages/viewpage.action?pageId=81352846

but with less informations and plots

**Comment by gprinz** [comment]
There is now a first version of the documentation. It cannot be finished before all details are known.

**Comment by tarrade** [comment]
Maybe add on sort paragrah for the model on Confluence and this is done ;-)

**Comment by gprinz** [comment]
Description of BigQuery Tables: https://confluence.axa.com/confluence/display/KBData/Technical+Ressources
