### ISSUE TITLE
Test unit for beam NLP preprocessing function

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#15]
add a test unit with beam to test all preprocessing functions with dummy data (small table in BigQuery with empty body, wrong encoding ...)

https://semaphoreci.com/community/tutorials/testing-python-applications-with-pytest
https://pythontesting.net/framework/pytest/pytest-introduction/

we have pytest install but I think unitest
https://www.slant.co/versus/9148/9149/~unittest_vs_pytest

it seems pytest is better

**Comment by gprinz** [comment]
Interesting: Most of the people do not test private methods (https://softwareengineering.stackexchange.com/questions/380287/why-is-unit-testing-private-methods-considered-as-bad-practice). Nevertheless, it makes sense in our case.
