### ISSUE TITLE
Classical ML Models

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#16]
When the NLP preprocessing is done, you can start with classical ML on a subset of the data using scikit_learn (Naive Bayes or SM).

You can find some example I did below:
https://github.axa.com/AXACH-CCDA/proj_claim_triage_arag/blob/master/notebook/Model%20Exploration.ipynb

or recently here:
https://github.axa.com/AXACH-CCDA/proj_autoindexing/blob/master/notebook/2-models.ipynb

**Comment by gprinz** [comment]
I have already made a model with scikit-learn earlier. I will adapt it as described in #30.

**Comment by tarrade** [comment]
base implementation is done. Need fine tuning when we will be able to process all the data
