### ISSUE TITLE
Running Beam pipeline with the full dataset of 32 GB of data -> ok [~83 CHF]

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#19]
This is only for Dataflow for the Thirsday and Friday:
2.76 CHF for 1'000 element
if we have 30 time more elements, the cost will be around ~83 CHF which is ok.

![image](https://user-images.githubusercontent.com/12021701/68996598-7f301780-089c-11ea-9f8c-e72ac4be8c26.png)

**Comment by tarrade** [comment]
You can lauch the full production on Monday. Hopefully with the new quotas, it will be ok and better than Friday

**Comment by gprinz** [comment]
Much less expensive than I have expected.

**Comment by tarrade** [comment]
between 3-5 CHF for 3:40 hours of Beam, not bad
 
![image](https://user-images.githubusercontent.com/12021701/69146099-62c7f100-0acf-11ea-9d34-14675f1c5eb0.png)
