### ISSUE TITLE
Migrate notebooks in the main folders [01-xxx to 05-xxx] with good name

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#20]
The idea is to have only one place with official notebook

![image](https://user-images.githubusercontent.com/12021701/69011022-42305780-0966-11ea-874d-d1bd81a6ece6.png)

Try to get a simple name ;-) the following one need to be fixed ;-)

![image](https://user-images.githubusercontent.com/12021701/69011063-a7844880-0966-11ea-8c07-86748a1061b4.png)

**Comment by gprinz** [comment]
Will be visible with the next commit.
