### ISSUE TITLE
Folder structure for the python code

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#21]
I added new folders for the code. I think for now this is good enought and later when we are doing training and serving we may need to do some modifications.

![image](https://user-images.githubusercontent.com/12021701/69011176-0c8c6e00-0968-11ea-8716-cb84bdf0117e.png)

python code should go most of the time in these sub folders.

can you move your pre-processing code in the corresponding folder ? don't use number like "01" for the name of the file. Also you don't need to specify the technology used like "beam". nlp_text_processing is good enought. Some of this could be done with Tensorflow with tf.text of we use Tensorflow later so better to said what the code is doing instead of the tools used.

**Comment by gprinz** [comment]
Restructuring will be visible after the commit.
