### ISSUE TITLE
 Dataflow: using Private IP's instead of Public IP addresses

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#22]
Using Public IP adresses is not optimal and is maybe a reason why we have issue with quotas.

Before doing the big production, just switch to private IP

```
from apache_beam.options.pipeline_options import WorkerOptions
google_cloud_options.region = 'europe-west1' #region    options.view_as(WorkerOptions).network = 'default'
options.view_as(WorkerOptions).use_public_ips=False
options.view_as(WorkerOptions).zone = 'europe-west6-a' #zone
```
I activated "Private Google Access" for Zurich:
https://medium.com/@harshithdwivedi/how-disabling-external-ips-helped-us-cut-down-over-80-of-our-cloud-dataflow-costs-259d25aebe74

I did some test and I git crashes at the end. I suspect issue with input/output BigQuery not beeing in the same zone.

By the way, I didn't see any of your test with a small dataset: endpoing west1 and workers west6. You should be sure this is working before sending the full production ;-)

**Comment by gprinz** [comment]
@tarrade That makes sense. But when I make a test, there is no issue with reading from and writing to BigQuery.

**Comment by gprinz** [comment]
I observe the same problem. Thus, I will migrate all our data to europe-west1 and check if the problem persists.

**Comment by gprinz** [comment]
@tarrade The problem does not occur anymore. Nevertheless, it is not possible to run a job with more than 6 workers due to the limit in the disk space.

![image](https://user-images.githubusercontent.com/32190139/69129512-cdb50000-0aae-11ea-88a6-c7ac27c06e68.png)

**Comment by tarrade** [comment]
@gprinz thanks for the test. I was mnitoring your job. I will update the qutoas.

**Comment by gprinz** [comment]
@tarrade I'm not sure if we have to update the quota. Maybe, we can just update the disk space of the workers, I will check that.

**Comment by tarrade** [comment]
very good point:

By default each VM needs a storage of 250 GB therefore for 100 instances it would be around 25TB. Please check the disk size of the workers that you are using and set the Persistent Disk quota under Compute Instances appropriately. 

which is maybe too much

**Comment by tarrade** [comment]
disk_size_gb, minimum is 30 GB, I will suggest 50 GB. Which means we need 5000 GB disk which is almost what we have. Do you want to try that ?

**Comment by gprinz** [comment]
I'm not sure how much disk space is required. I try 50 GB for the moment, let's see what happens...

**Comment by tarrade** [comment]
seems to work. Closing for now. Reopen it is new issue appear with this run
