### ISSUE TITLE
Change Autosave Directory of JupyterLab

### ISSUE THREAD

**Issue by gprinz** [tarrade/proj_NLP_text_classification_with_GCP#26]
Specify a single directory, so that JupyterLab trashes not the project by adding _.ipynb_checkpoints_ to every subfolder of the project.

https://github.com/jupyterlab/jupyterlab/issues/5809

**Comment by tarrade** [comment]
should be fix now. Need more test but closing for now.

**Comment by tarrade** [comment]
it is working and it goes here: /home/.jupyter_autosave
