### ISSUE TITLE
Memory Leakage of SpaCy

### ISSUE THREAD

**Issue by gprinz** [tarrade/proj_NLP_text_classification_with_GCP#29]
We are using version 2.1.8 of SpaCy which is subject to memory leakage. My test:

![image](https://user-images.githubusercontent.com/32190139/69642645-61b03a00-1062-11ea-8a7b-1e1b42ac001d.png)

Reference: [Stackoverflow](https://github.com/explosion/spaCy/issues/3618)

Problem: SpaCy makes use of [Cython](https://en.wikipedia.org/wiki/Cython), so that garbage collection gets important.

**Comment by gprinz** [comment]
Updating SpaCy to the most recent version (2.2.3) and installing en-core-web-sm (2.2.5). There is no memory leakage anymore:

![image](https://user-images.githubusercontent.com/32190139/69643979-4fcf9680-1064-11ea-9c4d-9b0900453591.png)

**Comment by gprinz** [comment]
@tarrade Shall we rerun the DataFlow process tomorrow with the new version of SpaCy?

**Comment by tarrade** [comment]
The version 2.2.3 seems to fix the issue until now (14M elements processed so far). Let see if this fixed all the issues or is new one appears.
