### ISSUE TITLE
Error message when Parallelizing Training with Scikit-Learn

### ISSUE THREAD

**Issue by gprinz** [tarrade/proj_NLP_text_classification_with_GCP#35]
One among many errors:

> A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGKILL(-9)}

**Setup monitoring for the VM with Stackdriver and increase the memory eventually.**

**Comment by gprinz** [comment]
[Stackdriver agent](https://app.google.stackdriver.com/settings/accounts/agent?project=nlp-text-classification)

**Comment by gprinz** [comment]
Better install the monitoring agent

`curl -sSO https://dl.google.com/cloudagents/install-monitoring-agent.sh
sudo bash install-monitoring-agent.sh`

Then, in Stackdriver go to Ressources>instances and choose the desired instance. From this, it gets clear that scikit-learn consumes a lot of memory when it starts parallelizing:

![image](https://user-images.githubusercontent.com/32190139/69866146-96f79a80-12a3-11ea-9193-888d3117f254.png)

Notice: A VM with 14GB (higher than the chosen dataset) has been used and the CPU load gets not higher than 50% (16 cores).

Further problem: With scikit-learn, not all processes can be palatalized.

**Comment by gprinz** [comment]
Using a pandas DataFrame of 1.5GB for training a Naive Bayes model fails when using all 16 cores and 60 GB RAM. More RAM is required. Let's check how much RAM it requires actually by increasing it again....

But in practice, mini-batches must be used for the training....
https://scikit-learn.org/stable/modules/computing.html
https://scikit-learn.org/stable/auto_examples/applications/plot_out_of_core_classification.html#sphx-glr-auto-examples-applications-plot-out-of-core-classification-py

**Comment by gprinz** [comment]
The model gets trained with the subset of 1.5 GB in about 15 minutes with 16 cores and 128 GB RAM.

![image](https://user-images.githubusercontent.com/32190139/69870837-72a2ba80-12b1-11ea-84da-c6aaa103aedd.png)
![image](https://user-images.githubusercontent.com/32190139/69870881-8a7a3e80-12b1-11ea-959f-d2cbd2db6202.png)

The costs are small (about one Dollar per hour, i.e. 0.25 Dollar for this training run). However, this is not scalable, because the amount of RAM explodes when more CPUs are used. Besides the mini-batches, the following would be a good idea:

https://datascience.stackexchange.com/questions/34416/scikit-learn-n-jobs-parameter-on-cpu-usage-memory

This reduces the amount of memory needed, but increases the processing time. However, it allows to increase the number of CPUs which compensates the higher processing time.

**Comment by tarrade** [comment]
summary:
- all Stackdriver agents are already pre-installed on the VM
- yes, with scikit-learn, not all processes can be parallelized and we need to use the one that have such implementation
- I need to read all links but I guess here what they can mini-batches this is cross validation because they have a so small dataset that they cannot use 20% for test only.

**Comment by gprinz** [comment]
**Problem**
Mini-batches not supported for 
- hyper-parameter tuning
- pipelines
- a lot of estimators (e.g. TfidfVectorizer)

**Comment by gprinz** [comment]
At the moment, there is always the problem that the memory consumption is not a problem for a long time, but shows a peak after a while causing the training process to crash.

![image](https://user-images.githubusercontent.com/32190139/69949563-0bc01400-14f2-11ea-8097-7d6b9de2d535.png)

Furthermore, it is quite unclear how scikit-learn handles multiple _n_jobs_ arguments:
https://stackoverflow.com/questions/59136430/how-does-scikit-learn-handle-multiple-n-jobs-arguments

**Comment by gprinz** [comment]
Conclusions from all the testings:

The memory usage explodes with large datasets if training is performed in parallel. The memory consumption is further increased if hyperparameter tuning is performed. There are a lot of other users reporting the same problem, but there seems to be no practicable solution at the moment other than just avoid parallel processing of large datasets with scikit-learn.

**Comment by gprinz** [comment]
The reason why scikit-learn consumes a vast amount of memory is that it is required to create multiple processes for parallelized execution which do not have a common memory space. Accordingly, the data must be loaded multiple times into the memory. Threading is not an option due to GIL (Global Interpreter Lock).

https://stackoverflow.com/questions/200469/what-is-the-difference-between-a-process-and-a-thread
https://realpython.com/python-gil/
https://stackoverflow.com/questions/59136430/how-does-scikit-learn-handle-multiple-n-jobs-arguments/59143472#59143472

**Comment by tarrade** [comment]
This may be an option is this is just a wrapper around scikit-learn:
- could be use on the VM
- I don't think we can use that for the AI Platform Training
https://docs.google.com/presentation/d/e/2PACX-1vSYCry8AWCGv3zMY8ELc_EB1DCsh4sPzMRLDV0NKl1_5xYGKuF6T7NzBMEZ6mm23OgebOVNzBiMPI5Z/pub?start=false&loop=false&delayms=6000#slide=id.g6fc2ea3704_0_72
