### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#40]
How much unique label did you select when you did the preprocessing with Dataflow ?

Here a query that mimic the issue I introduced in the old version of my code:
```
SELECT
   ARRAY_TO_STRING(tags, '----') AS labels,
   COUNT(ARRAY_TO_STRING(tags, '----')) AS cnt
FROM
  `nlp-text-classification.stackoverflow.posts_preprocessed` 
  
GROUP BY labels

ORDER BY cnt DESC
```
here I didn't unested the list when we have multiple lable and I just created a label that join the list with '----' in the middle. You can fix the code if you want.

![image](https://user-images.githubusercontent.com/12021701/70419379-9a3e1380-1a65-11ea-9a9c-4534409158ac.png)

- we have 21M without any lablels
- we have a huge number of labels (63'000) and this is responsible to blow the memory

maybe you can fix the BigQuery code if you want to unest the list and have a correct number of label ? This should then match what you did in the preprocessing code.

**Comment by gprinz** [comment]
Thank you so much for investigating on this issue! I had no time to look at it due to email triage project.

I have to take a closer look at your observations. The data selection contains 50 unique tags (empty tags are not allowed) only. Your findings might explain why I have observed differences between your and mine code.

I see that your have used a machine of 60GB for the training. Which memory load did you observe? Originally, when working with 1.5 GB (without parallelization), the memory load was also not too high.

**Comment by tarrade** [comment]
This is not needed anymore, n1-standard-4 is good enought. Memorty is not an issue. Now we get back to the issue that it run on one CPU and then it takes 8h to process 2.5M of events. In this condition it will be difficult to do hyper parameter tuning. It seems that adding data didn't bring much. I see the same accuray betwee 10'000, 200'000 and 2.5 M events. Let see how we can speed up by using other model. Partial fitting can help for memory issue not speed issue and their is some overheard.

**Comment by tarrade** [comment]
Here the correct query:
```
SELECT
 labels,
 COUNT(labels) AS cnt
FROM
  `nlp-text-classification.stackoverflow.posts_preprocessed`, UNNEST(tags) labels
  
GROUP BY labels

ORDER BY cnt DESC
```

which give 50 labels as expected:
![image](https://user-images.githubusercontent.com/12021701/70738939-0ba3ed80-1d16-11ea-9795-90bc93edf419.png)

the wrong assumption I made created combination of tag as new tags and then we end up with up of 63k tags which was causing memory leak.
