### ISSUE TITLE
Dataflow: Migration from legacy to audit log [---> not needed]

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#41]
I have been confirmed by the Big Data experts that none of the Dataflow (legacy) activity log entries will be discontinued on June 1st, so there is no action requiered on your part regarding this matter.
 The explanation for this is that the "Migrating from activity logs to audit logs" [1] page, which is from the Google Compute Engine documentation, states that (only) "**Some** activity log entries will be discontinued on June 1, 2020", and in that sentence there is a link to the deprecated legacy activity log entries table [2], where you can find the specific resource types affected, which are all for GCE.
 Please let me know if you have any more questions.
 Best regards,
 Arnau Carreras
 Google Cloud Support, Barcelona.
 [1] https://cloud.google.com/compute/docs/logging/migrating-from-activity-logs-to-audit-logs
 [2] https://cloud.google.com/compute/docs/logging/activity-logs#deprecated_activity_log_entries

**Comment by tarrade** [comment]
You can close this ticket when you have read the info from the GCP support team. Nothing need to be done ;-)

**Comment by gprinz** [comment]
Good explanation, thank you for clarifying this with the Google support team!

**Comment by tarrade** [comment]
GGP team need to improved their doc and communication by email ;-)
