### ISSUE TITLE
Problem with Git

### ISSUE THREAD

**Issue by gprinz** [tarrade/proj_NLP_text_classification_with_GCP#43]
@tarrade I currently have a problem with Git, so that I cannot push my new module without trashing our entire project folder. I have to fix this problem first on Monday. 

![image](https://user-images.githubusercontent.com/32190139/70815250-72381280-1dcd-11ea-8f51-0b8c7122abd8.png)

**Comment by tarrade** [comment]
Good luck, this is always painfull to fix ;-)

**Comment by gprinz** [comment]
1. Remove the environment locally
2. Unstage files by using _git reset_
3. remove the folder env/env by using _rm -rf env_
4. Recreate the environment
