### ISSUE TITLE
Random Forest: next steps

### ISSUE THREAD

**Issue by tarrade** [tarrade/proj_NLP_text_classification_with_GCP#44]
Next steps
- [x]  created a pipeline using Random Forest
- [x] commit code (github push issue)
- [x] train it on the AI Platform :200'000 then 2.5'000'000 and 15'000'000 events)
- [x] hyperparameter tunning on the AI Platform (full or partial dataset)

**Comment by gprinz** [comment]
Random Forest in Jupyter Lab:
![image](https://user-images.githubusercontent.com/32190139/70904978-017a3b80-2003-11ea-8775-8692f2bc1d8f.png)

Random Forest when executed by cell magic:
![image](https://user-images.githubusercontent.com/32190139/70904376-78aed000-2001-11ea-93ca-520374c63848.png)

**Comment by gprinz** [comment]
The problem is not within scikit-learn but rather the code providing the data to the model. The code snippet

`train_df,` eval_df = create_dataframes(frac, eval_size, nb_label)

takes a very long time to finish. Accordingly, the screenshots from above do not show both the training process. 

Next steps: 1) Code refactoring, 2) improve RF model and 3) proceed as described at the beginning

**Comment by gprinz** [comment]
@tarrade 
The problem we discussed yesterday was related to lambda functions. The situation is as follows:

**Not everything can be pickled (easily), though: examples of this are generators, inner classes, lambda functions and defaultdicts. In the case of lambda functions, you need to use an additional package named dill. With defaultdicts, you need to create them with a module-level function.**
Source: https://www.datacamp.com/community/tutorials/pickle-python-tutorial

Furthermore, the module should be saved together with metadata: https://www.mikulskibartosz.name/how-to-save-a-machine-learning-model-into-a-file/

**Comment by gprinz** [comment]
Solved by changing

`lambda string: string.split()`

to

`def split_string(string: str):
    return string.split()`

**Comment by tarrade** [comment]
https://cloud.google.com/ml-engine/docs/custom-prediction-routines

**Comment by gprinz** [comment]
In addition, functions can only be pickled if defined at the top level of a module:
https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled

For me another reason to prefer tensorflow.

**Comment by tarrade** [comment]
done in Vertex AI fro TF and PT
