### ISSUE TITLE
Stop file execution

### ISSUE THREAD

**Issue by gprinz** [tarrade/proj_NLP_text_classification_with_GCP#46]
Using cell magic for executing a Pythons script is very neat.

![image](https://user-images.githubusercontent.com/32190139/70904670-3934b380-2002-11ea-8bdd-335f1d281647.png)

But clicking the stop button in Jupyter Lab does not stop the execution of the script. Instead, bash must be used to kill the process.

Goal: Find a more convenient way to accomplish this.

**Comment by tarrade** [comment]
using bash and script in pycharm is the best option so far
